name = "earnix-bot"
main = "worker.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
keep_vars = true

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
